include/mlm_client.h, src/mlm_client.c, src/mlm_client.xml, src/mlm_client_engine.inc, src/mshell.c
Solution: fixed in zproto, regenerated here.
=> Problem: can't trace client side construction / connect

src/mlm_client_engine.inc, src/mlm_server.c, src/mlm_server.xml, src/mlm_server_engine.inc
Solution: dispatch service if new workers arrive.
Fixes #72
=> Problem: server does not dispatch on new SERVICE OFFER

README.md
Solution: change Malamute address from
git://github.com/malamute/malamute-core.git to
git://github.com/zeromq/malamute.git
=> Problem: wrong Malamute repository address

AMQP.md
=> Problem: Why is Malamute not an official ZeroMQ project?

.gitignore, issues/issue_81.c, src/malamute.c, src/mlm_client.c, src/mlm_client.xml, src/mlm_client_engine.inc, src/mlm_server_engine.inc
Solution: fixed in zproto and here, see PR 272 in zproto.
Test case issues/issue_81 shows correct behavior now.
=> Problem: client heartbeating is not working

.gitignore, issues/issue_87.c, issues/malamute.cfg, src/mlm_msg.c, src/mlm_msg.h, src/mlm_server.c
Solution: need to take copy of content before distributing.
Fixes #87
=> Problem: stream data sent to >1 client loses its content

src/mlm_server.c
Solution: free self->address before second strdup
=> Problem: make memcheck fails

project.xml
Solution: remove this, as czmq already pulls it in.
=> Problem: specifies zmq as dependency (unneeded)

Dockerfile, project.xml
Solution: backport to zproject and regenerate here
=> Problem: Dockerfile is made by hand

doc/mlm_client.doc, doc/mlm_client.txt, doc/mlm_proto.doc, doc/mlm_proto.txt, doc/mlm_server.doc, doc/mlm_server.txt
Solution: regenerate documentation manually
cd doc/; find . -name '*.txt' | xargs -L1 ./mkman
=> Problem: man mlm_client is obsolete

.travis.yml, ci_build.sh
Solution: fix various issues (see individual commits)
=> Problem: CI is broken

src/malamute.c
Solution: revert 916a7e
Also updated copyright year for fun.
=> Problem: malamute.c cannot build using malamute.h

Findczmq.cmake, Findlibsodium.cmake, Findlibzmq.cmake, ci_build.sh, configure.ac
Solution: regenerate via zproject.
=> Problem: CMake find package support was broken

configure.ac
Solution: do .git check conditioinally.
=> Problem: can't check for files during cross-compilation

api/mlm_client.xml, include/mlm_client.h
Solution: generate unfinished model via zproto (to be cleaned up)
=> Problem: lack client API model

src/mlm_client_engine.inc
Solution: fixed in zproto, regenerated here.
=> Problem: set_verbose was not working (and crashed)

src/Makemodule.am
Solution: regenerate from zproject
=> Problem: still using .xml extension for APIs

bindings/python/README.md, bindings/python/malamute_client.py, setup.py
Most notably "python setup.py install" now works.
=> More work on python bindings

builds/check_zproto/ci_build.sh
=> Problem: path to mlm_*.xml files are wrong

builds/check_zproto/ci_build.sh
=> Problem: check_zproto ci_build is not verbose

.travis.yml
Solution: try to get newer version
=> 	Problem: default Travis CI uses git 1.9.1

Dockerfile-dev, Makefile.am, configure.ac
=> Problem: no Dockerfile to test code from working dir

bindings/python/malamute/__init__.py
=> Problem: wrong trailing comma

CMakeLists.txt, Makefile.am, configure.ac
=> Problem: code not in line with zproject

configure.ac
Solution: regenerate from zproject to fix it
=> Problem: sistemd-units config option is broken

configure.ac, src/Makemodule.am
Solution: fixed in zproject and regenerate project
=> Problem: .cfg file was installed only with systemd integration

builds/gyp/README.md
Solution: Regenerated Malamute using zproject/tstgenbld.sh
For details, see https://github.com/zeromq/zproject/pull/587
This time, without '-target:*' in GSL command
=> Problem: Malamute not using latest ZPROJECT gsls

api/mlm_client.api, src/mlm_client_custom.xml
=> Problem: zproto uses <api> tag instead of <header> for zproject

api/mlm_client.api, src/mlm_classes.h, src/mlm_server_engine.inc
Solution: regenerate malamute with new zproto and zproject
=> Problem: malamute is generated with old zproto and zproject

src/mlm_server.xml, src/mlm_server_engine.inc
Solution: send "error" message back to the client (so client can start "reconnection" procedure)
=> Problem: if malamute in state "settling" there is no way from this state

src/mlm_client.xml, src/mlm_client_engine.inc
Solution: stay in the same state and wait for the responce
=> Problem: set_* methods can hang forever, if PONG is received

project.xml
Solution: added vs2013 target to project.xml
=> Problem: VS2013 project files not being generated

include/mlm_client.h, include/mlm_library.h, src/mlm_classes.h, src/mlm_client.c, src/mlm_selftest.c
Solution: reorganize the code + memory leak + add comments
=> Problem: make code cause some tests disappear

src/mlm_client.c
Because any of two workers can receive a request
Solution: check both variants
P.S. this issue was found by Travis
=> Problem: test is not reliable

src/mlm_client.c
Solution: use different connection endpoints
=> Problem: tests occasionally failed

Makefile.am, project.xml, src/Makemodule.am, src/mlm_classes.h, src/mlm_mailbox_bounded.c, src/mlm_mailbox_bounded.h, src/mlm_selftest.c
Solution: implement bounded mailbox
This patch only adds implmentation of bounded mailboxes. The broker
itself does not use this new type of mailbox yet.
=> Problem: mailboxes can grow indefinitely

src/mlm_stream_simple.c
Solution: rename them to s_stream_new &Ko
=> Problem: s_self_new & Ko ambiguos function names

src/mlm_stream_simple.c
Solution: fix naming and constructor
=> Problem: stream engine needs small improvements

src/mlm_server.c
Solution: dispatch single message instead of going through the whole queue
=> Problem: message dispatching gets slow when service queues grow large

src/malamute.cfg.in, src/mlm_server.c
=> Problem: broker uses unbounded mailbox

src/malamute.cfg.in, src/mlm_server.c
Solution: Change implementation to limit the amount of memory used
=> Problem: Service queue limit is the maximum number of messages

src/mlm_mailbox_bounded.c
Solution: Limit the amount of memory used by mailbox
=> Problem: Bounded mailbox actor limits the number of messages

src/malamute.cfg.in, src/mlm_mailbox_bounded.c, src/mlm_server.c
Solution: use size_t data type
=> Problem: mailbox size limit was stored as int

packaging/debian/rules, packaging/redhat/malamute.spec
=> Problem: out of date with zproject

include/mlm_library.h, src/mlm_classes.h, src/mlm_client.c, src/mlm_client.dot, src/mlm_client.xml, src/mlm_client_engine.inc, src/mlm_proto.c, src/mlm_selftest.c, src/mlm_server_engine.inc
Solution: 1. Check regexp in malamute before doing any action
2. Regenerate project with new zproto
3. add test
=> Problem: errors with regex pattern are not reported back to user

issues/issue_213/build.sh, issues/issue_213/reproduce.c
=> PROBLEM: Don't have bug reproduction code

src/mlm_server.c
Solution: add lowlevel-api + test
=> Problem: user wants to know the list of known streams

.travis.yml
Solution: add valgrind job to the list
=> Problem: Travis does not run valgrind test

src/mlm_server.c
asserts like these:
assert (streq (pop, "Karol") || streq (pop, "Tomas") || streq (pop,
"Alenka"));
expand so much that it triggers -Wno-overlength-strings
SOLUTION: asserts with || (or's) were a quick dirty hack anyway. Make a
real
list of expected values and query it for received values.
---
PROBLEM #2: sleeps in test too long
zlock_sleep (500); (half a second) is used too many times, it adds up
and the
`make check`;
SOLUTION: change them form 500 to 100
---
PROBLEM #3: STREAMLIST commands tests removal of stream that currently
does
nothing.
SOLUTION: change the test case from removal of stream to addition
=> PROBLEM: assert expand too long on older systems (issue #223)

.gitignore, Dockerfile, Makefile.am, acinclude.m4, bindings/jni/ci_build.sh, bindings/lua_ffi/malamute_ffi.lua, builds/check_zproject/ci_build.sh, builds/cmake/ci_build.sh, builds/gyp/platform.h, ci_build.sh, configure.ac, packaging/debian/rules
=> Problem: CI test has been broken for a while

.travis.yml, builds/check_zproject/ci_build.sh, builds/cmake/ci_build.sh, packaging/debian/control, src/mlm_proto.c, src/mlm_server_engine.inc
=> Problems: not using packages in Travis CI builds, out of date with zproject and zproto

CMakeLists.txt, configure.ac, project.xml
Solution: add it and regenerate
=> Problem: ABI not set in project.xml

.travis.yml, CMakeLists.txt, bindings/jni/build.gradle, builds/cmake/ci_build.sh
Solution: regen from zproject and add CMake to Travis list
Fixes #98
=> Problem: cmake build does not install malamute binaries, Travis does not check CMake

packaging/debian/malamute.install, packaging/redhat/malamute.spec
Solution: regenerate from zproject
=> Problem: RPM builds broken on SUSE/RHEL/CENTOS

doc/mlm_proto.doc, doc/mlm_proto.txt, include/mlm_proto.h, src/Makemodule.am, src/mlm_proto.c, src/mlm_server_engine.inc
Solution: run make code to regenerate
=> Problem: out of date with zproto, fails to build with GCC 7

.travis.yml
=> Problems: travis.yml out of date, no secure key for releases

src/mlm_client_engine.inc
Solution: regenerate from zproto
=> Problem: build broken with GCC 7

src/mlm_server.c
=> Problem: Recent changes I made seem to have broken the build

CMakeLists.txt, Makefile.am, bindings/python/malamute/_malamute_ctypes.py, ci_build.sh, configure.ac, packaging/obs/_service
Regenerate the project and fix test with cmake (we need to run tests from source_dir (and not build directoryàà
=> Update and small fix

src/mlm_client.c, src/mlm_server.c, src/mshell.c
Solution: replace tabs to 4 whitespaces and remove trialling whitespaces
=> Problem: files had identation problems not following CLASS RFC

src/mlm_server.c
client instance was not using the cleaner
approach to cleaning internal properties
and instead manually free'ing them after
a call to zhashx_delete ().
Solution: set the hashx destructor for client_t
and remove free from client_terminate () which
is called at a later time.
=> Problem: client instance not using hashx destructor

src/mlm_server.c
Please, wait for travis to complete before merging this. I've run `make memcheck` locally and it doesn't shows up any leaks.
Also, It's working for my application as well and leaks are no longer present according to valgrind.
=> Problem: client address cleaning not covering all cases

api/mlm_client.api, bindings/python/malamute/_malamute_ctypes.py, include/mlm_client.h
=> Fix memory leak with recv

CMakeLists.txt, bindings/python_cffi/malamute_cffi/cdefs.py, src/mlm_classes.h
Solution: regenerate using recent zproject
=> Problem: CI fails on check_zproject job

src/malamute.c
Solution: use the stringified version macros
from include/mlm_library.h
=> Problem: malamute server welcome message has old hardcoded version

.travis.yml
Solution: add the 3 encrypted tokens so that the next release will
automatically get binary packages on OBS
=> Problem: binary release builds through OBS not set up

NEWS, bindings/python_cffi/malamute_cffi/cdefs.py
Solutions: add one with the major changes since 1.0 and regenerate
=> Problems: no NEWS file, out of date with zproject

src/mlm_client.xml, src/mlm_client_engine.inc
=> Pass messages to the application during confirming state

api/mlm_client.api, include/mlm_client.h, include/mlm_server.h, src/mlm_client.dot, src/mlm_client_engine.inc, src/mlm_proto.bnf, src/mlm_proto.c, src/mlm_server_engine.inc
Solution: regenerate using more recent one :)
=> Problem: can't build with recent zproto

api/mlm_client.api, api/mlm_proto.api, include/mlm_client.h, include/mlm_proto.h, src/mlm_client.c, src/mlm_client.dot, src/mlm_client.xml, src/mlm_client_engine.inc, src/mlm_proto.bnf, src/mlm_proto.c, src/mlm_proto.xml, src/mlm_server.c, src/mlm_server.dot, src/mlm_server.xml, src/mlm_server_engine.inc
I was looking into implementing this until issue #282 was created. This solution allows the removal of a consumer from a specified stream. 
This is my first contribution to any zeromq project, so let me know if there is something I should do differently or change in order for the pull request to go through.
=> Remove consumer from a stream

src/mlm_client.c
Added a few lines in mlm_client_test to run a basic test for the new remove_consumer feature
=> Added remove_consumer test in mlm_client_test

src/mlm_client.c, src/mlm_client.cfg, src/mlm_server.c, src/mlm_server_engine.inc
Solution: regen from zproto and fix it
Fixes #294
=> Problem: Tests should not use fixed port numbers

src/mlm_server.c
=> Fix use after free in service dispatch

bindings/python/malamute/__init__.py
=> Fix few errors in Python binding

bindings/jni/build.gradle, bindings/jni/ci_build.sh, bindings/python_cffi/malamute_cffi/cdefs.py
Fix: regenerate zproject
Ref. https://github.com/zeromq/zproject/issues/1266
=> Problem: not aligned with zproject
