zeromq/malamute

src/Makemodule.am
Solution: use @prefix@/lib instead of libdir, which expands to
/usr/lib64 in rpm distros, where systemd does expects /usr/lib
=> Problem: service file bad location on 64bit rpm systems

src/zbits.c
Solution: stop using these macros.
=> Problem: min, max macros are not supported in CZMQ

src/mlm_server.c, tests/mlm_tests.c
The problem hits after N second, depending on the timeout in malamute.cfg.
What happens is that an existing old client thread wakes up, decides that
it's expired, and kills the client mailbox. The current active client
loses any messages waiting in the mailbox.
Solution: when registering a new client, force an expiration of any
existing client using the same address. This is the only way to safely
reconnect after an unexpected disconnect. If we reject new clients with
the same / existing address, we cannot reconnect until the timeout has
expired.
=> Problem: we lose mailbox messages when reconnecting with same address

src/mlm_client.c, src/passwords.cfg
Running make check on the latest master gets stuck. Culprit from the
bisect point of view seems to be commit c139362. In the fact, in the
light of this commit test seems to be4 stuck kinda correctly as two
clients shouldn't have the same name.
Solution: Use two different client names in the test
=> Problem: Can't run make check

src/malamute.cfg, src/mlm_client.c, src/mlm_client.cfg, src/mlm_perftest.c, src/mlm_server.c, src/mlm_tutorial.c, src/mshell.c
The default ipc endpoint is not portable to other systems
like OSX or Windows. Changed it to inproc and tcp where was
the case.
=> Changed default ipc endpoint to inproc and tcp for portability

src/malamute.c, src/malamute.service.in
Solution: enforce foreground mode of malamute via switch -f and update
unit file, so server/background config entry will be ignored.
=> Problem: Type=simple must not daemonize

include/mlm_client.h, src/mlm_client.c, src/mlm_client.xml, src/mlm_client_engine.inc, src/mlm_msg.c, src/mlm_msg.h, src/mlm_server.c
Solution: set this to stream name, as it should be.
Problem: sender is always empty in client API
Solution: return sender name properly
I extended the mlm_client.c self tests with checks for both these
problems.
Fixes #67
=> Problem: address is always empty in STREAM DELIVER

src/mlm_server.c
Solution: fix the NULL pointer dereference
The stacktrace is
#0  0x00007fcabb651a3d in deregister_the_client
(self=self@entry=0x7fcaac00df50) at src/mlm_server.c:574
#1  0x00007fcabb6527ab in s_client_execute
(self=self@entry=0x7fcaac00df50, event=<optimized out>) at
src/mlm_server_engine.inc:1089
#2  0x00007fcabb65345b in s_server_handle_protocol (loop=<optimized
out>, reader=<optimized out>, argument=0x7fcaac0008c0) at
src/mlm_server_engine.inc:1405
#3  0x00007fcabb3d1c7d in zloop_start (self=0x7fcaac0024b0) at
src/zloop.c:818
#4  0x00007fcabb6538b3 in mlm_server (pipe=0x1d99af0, args=0x4013fb) at
src/mlm_server_engine.inc:1448
#5  0x00007fcabb3bbb53 in s_thread_shim (args=0x1d96190) at
src/zactor.c:67
#6  0x00007fcaba4cd0a4 in start_thread (arg=0x7fcab3fff700) at
pthread_create.c:309 …
=> Problem: malamute segfaults when deregistering client

src/mlm_client_engine.inc
Solution: bool doesn't need to have the same size as int, so just to be
sure using int.
=> Problem: Self tests are crashing on ARM

builds/static/Dockerfile, builds/static/build.sh
Add a Dockerfile that builds a statically compiled malalute with MUSL libc.
Glibc was causing problems (see here http://permalink.gmane.org/gmane.network.zeromq.devel/27492), so I had to switch to MUSL libc, which is lighter and less hostile to static binaries (Read "The GCC/Linux developer community is sold on shared library executables" http://www.staticramlinux.com/BuildingStaticCompiler.html).
A complete build image is also available here:
https://hub.docker.com/r/zoobab/malamute-static/
$ docker pull zoobab/malamute-static
=> Add a Dockerfile that builds a statically compiled malalute with MUSL libc

src/mlm_perftest.c, src/mlm_tutorial.c, src/mshell.c
Solution: include mlm_classes.c instead of malamute.h in all of them.
=> Problem: Some executables are still broken.

.travis.yml, builds/check_zproject/ci_build.sh, ci_build.sh
zproject has not run
Solution: Add a build that fails if code in repo differs from
code generated with latest Travis
=> Problem: Travis does not let us know that

src/mlm_client.c, src/mlm_client.xml, src/mlm_client_engine.inc
Solution: 1. when terminated in start state make sure, we are going to terminate
2. instead of crashing on unkown even, just ignore it
3. set_consumer, set_producer, set_worker should return fail, if client is not connected
4. self test extended
=> Problem: termination of not connected client crashes the application

src/mlm_client.c, src/mlm_client.xml, src/mlm_client_engine.inc
Solution: stay in "start" state if connection ended with failure
=> Problem: cannot use mlm_client_connect two times, if first time returned with error

src/mlm_client.c, src/mlm_client.xml, src/mlm_client_engine.inc
, set_consumer, set_worker should return with the error.
missing test case for fast returned server.
Solution: return failure, if set producer/consumer/worked didn't work correctly
add a tst case.
=> Problem: if client didn't reconnect to the server, calls set_producer

CMakeLists.txt, bindings/jni/README.md, bindings/jni/build.gradle, bindings/ruby/lib/malamute/ffi/version.rb, builds/msvc/resource.rc, configure.ac, include/mlm_library.h, project.xml
After a release we must always update the working version number
so that anyone using it does not confuse it with the released code.
Solution: update project version to 1.1
=> Problem: released v1.0 via github

src/mlm_perftest.c
CZMQ removed zsys_allocs. Thus, we cannot use
it to check the number of allocations.
Solution: Remove it.
=> Problem: mlm_perftest.c is broken due to czmq changes

src/mlm_client.xml, src/mlm_client_engine.inc
Solution: after "destructor" event fired there is no way back to the "connected" state
=> Problem: client sometimes hangs in the destructor

src/mlm_client.xml, src/mlm_client_engine.inc
Solution: if we receive "ERROR" message from server after
destruction of the client started we should still destroy the client,
instead of starting the reconnection procedure
=> Problem: mlm_client_destroy can hang forever

src/mlm_client.xml, src/mlm_client_engine.inc
SOlution: 1. we can change  state only after all replat command were done, so if we receive PONG from server, we will state in "reconnecting state" 2. to be consistent with other links, when client goes to the "connected" state client should call "client_is_connected"
=> Problem: the change from "reconneting" to "connected" state is wrong

src/mlm_client.c, src/mlm_client.xml, src/mlm_client_engine.inc
SOlution: rename it
all other signal* functions are designed to send a
replay back to the caller API, but signal_unhandled_error
is not.
=> Problem: ambigous name of the function

include/mlm_client.h, src/mlm_classes.h, src/mlm_client.c, src/mlm_selftest.c
Solution: Created three new self tests for specific API sets:
1) mlm_stream_api
2) mlm_service_api
3) mlm_services_api
The difference between tests 2 and 3 is that mlm_service_api shows
how to use the service APIs with one requester, one worker, while that
mlm_services_api shows how to use the service API with two requesters
and two workers.
Also greatly increased the number of asserts in existing tests, making
sure no returned code goes without checking.
I believe that to be important in self tests.
Hopefully I correctly followed the unwritten rules of formatting required
such as space before the parenthesis in function calls and no camel case
of variable names. By the way, I even fixed this for some existing code.
If any of this code should be generated, I was not able to find the …
=> Problem: self tests can be improved

configure.ac, include/mlm_library.h
HI,
Here the fixes for correctly compile malamute using msys2 + mingw64 gcc.
DLL_EXPORT is automatically generated by libtool. I'm using this symbol + the indication of internal compilation put in the configure.ac in order to enable dllexport or not
=> Fix compilation with mingw64 using autotools

src/mlm_client.xml, src/mlm_client_engine.inc
Solution: set up the address in the message before reconnect to the right value
because field "address" in mlm_proto is used not only for client address set up
=> Problem: someclient are trying to reconnect with wrong address

src/mlm_client.c, src/mlm_client.xml, src/mlm_client_engine.inc
Solution: store client's address as a separate field in the structure
instead of storing it in self->args->address (because it  could be rewritten
by the call set_worker)
=> Problem: address of the client can disappear

include/mlm_server.h, src/mlm_server.c
Currently there is no way how to find out names of clients connected
to malamute server.
SOLUTION: Create malamute server (actor) command CLIENTLIST that
returns multipart string message with connected client names and
repeated command  as first frame.
=> PROBLEM: Can't query names of connected clients 

src/mlm_server.c
Solution: given the private classes symbols are intentionally not
exported, the self test functions cannot be called from the external
mlm_selftest binary.
Call them instead from the main class selftest function.
=> Problem: private classes self tests no longer ran

packaging/debian/malamute.dsc.obs
Solution: regenerate
Comments can go inline in d/control but not in the .dsc. Ops.
=> Problem: out of date with zproject

src/mlm_server.c
If the server is restarted and a client is still connected, it may
have a few CONNECTION_PING messages queued up on the socket which the
server will receive when it is restarted.  This is fine at the moment,
but in the case where the client does not then send CONNECTION_OPEN,
the server will try to deregister the client, and since the address
was never set, it segfaults.
Maybe this is only something I see because I'm working on a python
client and it's not well-behaved or something, but the server
shouldn't crash regardless, because even with well-behaved clients
this could happen if the client shuts down just after the server is
restarted.
Solution: cleanly handle the case of the client address being null.
Add a regression test.
=> Problem: server can segfault due to incomplete connections

src/mlm_server.c
Solution: destroy socket and server at end of incomplete connection
regression test.  (also fix indentation)
=> Problem: test does not clean up after itself

meson.build
Solution: write a basic meson.build file for malamute by hand, note
number of issues and push it upstream.
meson build is a generator (like CMake or zproject) of build recipes. It
uses ninja backend by default, but have an ability to generate builds
for MSVC and XCode. Like zproject it's quite opiniated and declarative
(unline WAF) and easy to write (unline CMake), so can be a great
match.
How to use:
mkdir build
meson . build/
ninja -v -C build
ninja -v -C build test
The final goal is to get zproject_meson.gsl, so this will give people
option to play with it.
=> Problem: want to play with meson build system

README.md
It's described in the protocol and white paper but not supported.
Solution: add a note in README.md to make it clear
=> Problem: it took me a long time to figure out that message confirmation is not implemented

src/mlm_server.c
When deregistering the client, it deletes the client
hash entry and then the mlm_server_engine.inc FSM
calls allow_time_to_settle ().
This routine currently sets a timer of 1000ms
and then teminate the client by calling
the zhash destructor and then client_terminate ().
This should be sufficient to free client internal
structures as client_terminate () frees the client
address, but for some reason valgrind shows memory
leaks, as shown below:
==5909== Memcheck, a memory error detector
==5909== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==5909== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright
info
==5909== Command: /usr/bin/malamute -f /usr/etc/malamute/malamute.cfg
==5909== Parent PID: 1
==5909==
==5909==
==5909== HEAP SUMMARY:
==5909==     in use at …
=> Problem: possible memory leak in deregistering the client

src/mlm_server.c
I see that commit 5d4a792 introduced the second strdup and d508a95 introduced zstr_free () before the second strdup (). 
@vyskocilm As you were the last to change this part, do you see a reason for keeping this?
=> Problem: redundant strdup ()/zstr_free () in register_client ()

src/mlm_client.c, src/mlm_server.c
Issue:
Some tests doesn't run on windows (cause: IPC)
Private class tests are now includes as a seperate test
For some reason NDEBUG is undefined (For enabling test in release? if it is the case it's an incomplete and a hacky solution)
On windows each test crash at the end because wsacleanup is called before zsys_shutdown (called by atexit)
Done:
Use inproc instead of ipc for tests (Windows compatibility)
Remove duplicated tests
Remove NDEBUG undef
Todo:
Find a way to call zsys_shutdown at the end of each tests?
Use another assert function always enabled in the test part of the code?
=> Improve tests

src/mlm_client.cfg, src/mlm_server_engine.inc
I'm not sure that the commit is correct, but since this commit https://github.com/zeromq/libzmq/commit/e546f9296e6002c0b3311c98cd5e308d3757807f
You must provide a domain for plain mechanism.
=> Fix zap auth with plain mechanism

src/mlm_server.c, src/mlm_server_engine.inc, src/mlm_stream_simple.c, src/mlm_stream_simple.h
The current code inserts a one second delay in the hope that any pending
stream traffic will be flushed before the client context is destroyed.
Under heavy load, this may not work and we end up with a use-after-free
in s_forward_stream_traffic(). Instead of relying on luck, do proper
reference counting on the client contexts.
=> Properly handle pending stream traffic after client disconnect

bindings/jni/CMakeLists.txt
The CMakeLists.txt in jni is outdated according to Findmalamute.cmake file generated (in 98ced58d8bd62142aba96552b725e32b1636b76a)
=> Fix CMakeLists.txt in jni

src/malamute.c
Solution: call it manually before exiting
=> Problem: Windows DLL builds cannot run zsys_shutdown in at_exit

src/malamute.c
zsys already allow `ZSYS_LOGSYSTEM` and `ZSYS_LOGSTREAM` to control this behavior. However the `zsys_set_logsystem` override those and does not leave any way for the user to use `ZSYS_LOGSYSTEM=false`. Note that unlike as stated by the previous comment, stdout is only used if logsystem is not used.
=> Use environment variable instead of hardcoded zsys config
